apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apache-server.fullname" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "apache-server.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "apache-server.fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 80
