apiVersion: v1
kind: service
metadata:
  name: {{ include "apache-server.fullname" . }}
spec:
  selector:
    app: {{ include "apache-server.fullname" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ .Values.service.type }}
